concurrent = 5
check_interval = 0

[[runners]]
  environment = ["GIT_SSL_NO_VERIFY=true"]
  tls-ca-file="/etc/gitlab-runner/certs/server.crt"
  url = "GITLAB_CI_URI"
  name = "RUNNER_NAME"
  token = "RUNNER_TOKEN"
  executor = "docker"
  limit = 10
  [runners.docker]
    privileged = true
    image = "alpine/git:latest"
    tls_verify = false
    disable_cache = true
    cache_dir = "/cache"
    volumes = ["/cache"]
